export const GLOBALTYPES = {
    //Modal
    CREATE_POST_MODAL_STATUS: 'CREATE_POST_MODAL_STATUS',
    EMOTION_MODAL_IN_CREATE_POST: 'EMOTION_MODAL_IN_CREATE_POST',
    EMOTION_MODAL_POSITION: 'EMOTION_MODAL_POSITION',
    FILE_MODAL_IN_CREATE_POST: 'FILE_MODAL_IN_CREATE_POST',
    INIT_FILE_MODAL_TYPE: 'INIT_FILE_MODAL_TYPE',

    //EmotionModal
    OPEN_EMOTION_MODAL: 'OPEN_EMOTION_MODAL',
    CLOSE_EMOTION_MODAL: 'CLOSE_EMOTION_MODAL',
    SET_TOGGLE_ICON_EL: 'SET_TOGGLE_ICON_EL',
    SET_EMOTION_VALUE: 'SET_EMOTION_VALUE',
    SET_TEXTAREA_EL: 'SET_TEXTAREA_EL',
    SET_EMOTION_CHANGE: 'SET_EMOTION_CHANGE'
} 